<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RumpunBidangIlmuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['kode' => '100', 'nama_bidang' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '110', 'nama_bidang' => 'Ilmu IPA', 'parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)', 'sub_parent_category' => ''],
            ['kode' => '111', 'nama_bidang' => 'Fisika', 'parent_category' => 'Ilmu IPA', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '112', 'nama_bidang' => 'Kimia', 'parent_category' => 'Ilmu IPA', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '113', 'nama_bidang' => 'Biologi (Dan Bioteknologi Umum)', 'parent_category' => 'Ilmu IPA', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '114', 'nama_bidang' => 'Bidang Ipa Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu IPA', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '120', 'nama_bidang' => 'Matematika', 'parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)', 'sub_parent_category' => ''],
            ['kode' => '121', 'nama_bidang' => 'Matematika', 'parent_category' => 'Matematika', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '122', 'nama_bidang' => 'Statistik', 'parent_category' => 'Matematika', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '123', 'nama_bidang' => 'Ilmu Komputer', 'parent_category' => 'Matematika', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '124', 'nama_bidang' => 'Bidang Matematika Lain Yang Belum Tercantum', 'parent_category' => 'Matematika', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '130', 'nama_bidang' => 'Kebumian Dan Angkasa', 'parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)', 'sub_parent_category' => ''],
            ['kode' => '131', 'nama_bidang' => 'Astronomi', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '132', 'nama_bidang' => 'Geografi', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '133', 'nama_bidang' => 'Geologi', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '134', 'nama_bidang' => 'Geofisika', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '135', 'nama_bidang' => 'Meteorologi', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '136', 'nama_bidang' => 'Bidang Geofisika Lain Yang Belum Tercantum', 'parent_category' => 'Kebumian Dan Angkasa', 'sub_parent_category' => 'Matematika Dan Ilmu Pengetahuan Alam (MIPA)'],
            ['kode' => '140', 'nama_bidang' => 'Ilmu Tanaman', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '150', 'nama_bidang' => 'Ilmu Pertanian Dan Perkebunan', 'parent_category' => 'Ilmu Tanaman', 'sub_parent_category' => ''],
            ['kode' => '151', 'nama_bidang' => 'Ilmu Tanah', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '152', 'nama_bidang' => 'Hortikultura', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '153', 'nama_bidang' => 'Ilmu Hama Dan Penyakit Tanaman', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '154', 'nama_bidang' => 'Budidaya Pertanian Dan Perkebunan', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '155', 'nama_bidang' => 'Perkebunan', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '156', 'nama_bidang' => 'Pemuliaan Tanaman', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '157', 'nama_bidang' => 'Bidang Pertanian & Perkebunan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pertanian Dan Perkebunan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '160', 'nama_bidang' => 'Teknologi Dalam Ilmu Tanaman', 'parent_category' => 'Ilmu Tanaman', 'sub_parent_category' => ''],
            ['kode' => '161', 'nama_bidang' => 'Teknologi Industri Pertanian (Dan Agroteknologi)', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '162', 'nama_bidang' => 'Teknologi Hasil Pertanian', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '163', 'nama_bidang' => 'Teknologi Pertanian', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '164', 'nama_bidang' => 'Mekanisasi Pertanian', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '165', 'nama_bidang' => 'Teknologi Pangan Dan Gizi', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '166', 'nama_bidang' => 'Teknologi Pasca Panen', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '167', 'nama_bidang' => 'Teknologi Perkebunan', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '168', 'nama_bidang' => 'Bioteknologi Pertanian Dan Perkebunan', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '169', 'nama_bidang' => 'Ilmu Pangan', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '171', 'nama_bidang' => 'Bidang Teknologi Dalam Ilmu Tanaman Yang Belum Tercantum', 'parent_category' => 'Teknologi Dalam Ilmu Tanaman', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '180', 'nama_bidang' => 'Ilmu Sosiologi Pertanian', 'parent_category' => 'Ilmu Tanaman', 'sub_parent_category' => ''],
            ['kode' => '181', 'nama_bidang' => 'Sosial Ekonomi Pertanian', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '182', 'nama_bidang' => 'Gizi Masyarakat Dan Sumber Daya Keluarga', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '183', 'nama_bidang' => 'Ekonomi Pertanian', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '184', 'nama_bidang' => 'Sosiologi Pedesaan', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '185', 'nama_bidang' => 'Agribisnis', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '186', 'nama_bidang' => 'Penyuluh Pertanian', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '187', 'nama_bidang' => 'Bidang Sosiologi Pertanian Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Sosiologi Pertanian', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '190', 'nama_bidang' => 'Ilmu Kehutanan', 'parent_category' => 'Ilmu Tanaman', 'sub_parent_category' => ''],
            ['kode' => '191', 'nama_bidang' => 'Budidaya Kehutanan', 'parent_category' => 'Ilmu Kehutanan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '192', 'nama_bidang' => 'Konservasi Sumberdaya Hutan', 'parent_category' => 'Ilmu Kehutanan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '193', 'nama_bidang' => 'Manajemen Hutan', 'parent_category' => 'Ilmu Kehutanan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '194', 'nama_bidang' => 'Teknologi Hasil Hutan', 'parent_category' => 'Ilmu Kehutanan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '195', 'nama_bidang' => 'Bidang Kehutanan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Kehutanan', 'sub_parent_category' => 'Ilmu Tanaman'],
            ['kode' => '200', 'nama_bidang' => 'Ilmu Hewani', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '210', 'nama_bidang' => 'Ilmu Peternakan', 'parent_category' => 'Ilmu Hewani', 'sub_parent_category' => ''],
            ['kode' => '211', 'nama_bidang' => 'Ilmu Peternakan', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '212', 'nama_bidang' => 'Sosial Ekonomi Perternakan', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '213', 'nama_bidang' => 'Nutrisi Dan Makanan Ternak', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '214', 'nama_bidang' => 'Teknologi Hasil Ternak', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '215', 'nama_bidang' => 'Pembangunan Peternakan', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '216', 'nama_bidang' => 'Produksi Ternak', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '217', 'nama_bidang' => 'Budidaya Ternak', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '218', 'nama_bidang' => 'Produksi Dan Teknologi Pakan Ternak', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '219', 'nama_bidang' => 'Bioteknologi Peternakan', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '221', 'nama_bidang' => 'Sain Veteriner', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '222', 'nama_bidang' => 'Bidang Peternakan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Peternakan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '230', 'nama_bidang' => 'Ilmu Perikanan', 'parent_category' => 'Ilmu Hewani', 'sub_parent_category' => ''],
            ['kode' => '231', 'nama_bidang' => 'Sosial Ekonomi Perikanan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '232', 'nama_bidang' => 'Pemanfaatan Sumberdaya Perikanan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '233', 'nama_bidang' => 'Budidaya Perikanan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '234', 'nama_bidang' => 'Pengolahan Hasil Perikanan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '235', 'nama_bidang' => 'Sumberdaya Perairan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '236', 'nama_bidang' => 'Nutrisi Dan Makanan Ikan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '237', 'nama_bidang' => 'Teknologi Penangkapan Ikan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '238', 'nama_bidang' => 'Bioteknologi Perikanan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '239', 'nama_bidang' => 'Budidaya Perairan', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '241', 'nama_bidang' => 'Bidang Perikanan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Perikanan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '250', 'nama_bidang' => 'Ilmu Kedokteran Hewan', 'parent_category' => 'Ilmu Hewani', 'sub_parent_category' => ''],
            ['kode' => '251', 'nama_bidang' => 'Kedokteran Hewan', 'parent_category' => 'Ilmu Kedokteran Hewan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '252', 'nama_bidang' => 'Bidang Kedokteran Hewan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Kedokteran Hewan', 'sub_parent_category' => 'Ilmu Hewani'],
            ['kode' => '260', 'nama_bidang' => 'Ilmu Kedokteran', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '270', 'nama_bidang' => 'Ilmu Kedokteran Spesialis', 'parent_category' => 'Ilmu Kedokteran', 'sub_parent_category' => ''],
            ['kode' => '272', 'nama_bidang' => 'Anestesi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '273', 'nama_bidang' => 'Bedah (Umum, Plastik, Orthopaedi, Urologi, Dll)', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '274', 'nama_bidang' => 'Kebidanan Dan Penyakit Kandungan', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '275', 'nama_bidang' => 'Kedokteran Forensik', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '276', 'nama_bidang' => 'Kedokteran Olahraga', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '277', 'nama_bidang' => 'Penyakit Anak', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '278', 'nama_bidang' => 'Ilmu Kedokteran Nuklir', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '279', 'nama_bidang' => 'Ilmu Kedokteran Fisik Dan Rehabilitasi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '281', 'nama_bidang' => 'Penyakit Tht', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '282', 'nama_bidang' => 'Patologi Anatomi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '283', 'nama_bidang' => 'Patologi Klinik', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '284', 'nama_bidang' => 'Penyakit Dalam', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '285', 'nama_bidang' => 'Penyakit Jantung', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '286', 'nama_bidang' => 'Penyakit Kulit Dan Kelamin', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '287', 'nama_bidang' => 'Penyakit Mata', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '288', 'nama_bidang' => 'Ilmu Kedokteran Fisik Dan Rehabilitasi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '289', 'nama_bidang' => 'Penyakit Paru', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '291', 'nama_bidang' => 'Penyakit Syaraf', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '293', 'nama_bidang' => 'Mikrobiologi Klinik', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '294', 'nama_bidang' => 'Neurologi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '295', 'nama_bidang' => 'Psikiatri', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '296', 'nama_bidang' => 'Radiologi', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '297', 'nama_bidang' => 'Rehabilitasi Medik', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '298', 'nama_bidang' => 'Bidang Kedokteran Spesialis Lain Yang Tercantum', 'parent_category' => 'Ilmu Kedokteran Spesialis', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '300', 'nama_bidang' => 'Ilmu Kedokteran (Akademik)', 'parent_category' => 'Ilmu Kedokteran', 'sub_parent_category' => ''],
            ['kode' => '301', 'nama_bidang' => 'Biologi Reproduksi', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '303', 'nama_bidang' => 'Ilmu Biologi Reproduksi', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '304', 'nama_bidang' => 'Ilmu Biomedik', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '305', 'nama_bidang' => 'Ilmu Kedokteran Umum', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '306', 'nama_bidang' => 'Ilmu Kedokteran Dasar', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '307', 'nama_bidang' => 'Ilmu Kedokteran Dasar & Biomedis', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '308', 'nama_bidang' => 'Ilmu Kedokteran Keluarga', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '309', 'nama_bidang' => 'Ilmu Kedokteran Klinik', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '311', 'nama_bidang' => 'Ilmu Kedokteran Tropis', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '312', 'nama_bidang' => 'Imunologi', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '313', 'nama_bidang' => 'Kedokteran Kerja', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '314', 'nama_bidang' => 'Kesehatan Reproduksi', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '315', 'nama_bidang' => 'Bidang Ilmu Kedokteran Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Kedokteran (Akademik)', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '320', 'nama_bidang' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'parent_category' => 'Ilmu Kedokteran', 'sub_parent_category' => ''],
            ['kode' => '321', 'nama_bidang' => 'Kedokteran Gigi', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '322', 'nama_bidang' => 'Bedah Mulut', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '323', 'nama_bidang' => 'Penyakit Mulut', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '324', 'nama_bidang' => 'Periodonsia', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '325', 'nama_bidang' => 'Ortodonsia', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '326', 'nama_bidang' => 'Prostodonsia', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '327', 'nama_bidang' => 'Konservasi Gigi', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '328', 'nama_bidang' => 'Bidang Spesialis Kedokteran Gigi Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Spesialis Kedokteran Gigi Dan Mulut', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '330', 'nama_bidang' => 'Ilmu Kedokteran Gigi (Akademik)', 'parent_category' => 'Ilmu Kedokteran', 'sub_parent_category' => ''],
            ['kode' => '331', 'nama_bidang' => 'Ilmu Kedokteran Gigi', 'parent_category' => 'Bidang Spesialis Kedokteran Gigi Lain Yang Belum Tercantum', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '332', 'nama_bidang' => 'Ilmu Kedokteran Gigi Dasar', 'parent_category' => 'Bidang Spesialis Kedokteran Gigi Lain Yang Belum Tercantum', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '333', 'nama_bidang' => 'Ilmu Kedokteran Gigi Komunitas', 'parent_category' => 'Bidang Spesialis Kedokteran Gigi Lain Yang Belum Tercantum', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '334', 'nama_bidang' => 'Bidang Ilmu Kedokteran Gigi Lain Yang Belum Tercantum', 'parent_category' => 'Bidang Spesialis Kedokteran Gigi Lain Yang Belum Tercantum', 'sub_parent_category' => 'Ilmu Kedokteran'],
            ['kode' => '340', 'nama_bidang' => 'Ilmu Kesehatan', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '350', 'nama_bidang' => 'Ilmu Kesehatan Umum', 'parent_category' => 'Ilmu Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '351', 'nama_bidang' => 'Kesehatan Masyarakat', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '352', 'nama_bidang' => 'Keselamatan Dan Kesehatan Kerja (Kesehatan Kerja; Hiperkes)', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '353', 'nama_bidang' => 'Kebijakan Kesehatan (Dan Analis Kesehatan)', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '354', 'nama_bidang' => 'Ilmu Gizi', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '355', 'nama_bidang' => 'Epidemiologi', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '356', 'nama_bidang' => 'Teknik Penyehatan Lingkungan', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '357', 'nama_bidang' => 'Promosi Kesehatan', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '358', 'nama_bidang' => 'Ilmu Asuransi Jiwa Dan Kesehatan', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '359', 'nama_bidang' => 'Kesehatan Lingkungan', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '361', 'nama_bidang' => 'Ilmu Olah Raga', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '362', 'nama_bidang' => 'Bidang Kesehatan Umum Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Kesehatan Umum', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '370', 'nama_bidang' => 'Ilmu Keperawatan Dan Kebidanan', 'parent_category' => 'Ilmu Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '371', 'nama_bidang' => 'Ilmu Keperawatan', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '372', 'nama_bidang' => 'Kebidanan', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '373', 'nama_bidang' => 'Administrasi Rumah Sakit', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '375', 'nama_bidang' => 'Entomologi (Kesehatan, Fitopatologi)', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '376', 'nama_bidang' => 'Ilmu Biomedik', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '377', 'nama_bidang' => 'Ergonomi Fisiologi Kerja', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '378', 'nama_bidang' => 'Fisioterapi', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '379', 'nama_bidang' => 'Analis Medis', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '381', 'nama_bidang' => 'Fisiologi (Keolahragaan)', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '382', 'nama_bidang' => 'Reproduksi (Biologi Dan Kesehatan)', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '383', 'nama_bidang' => 'Akupunktur', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '384', 'nama_bidang' => 'Rehabilitasi Medik', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '385', 'nama_bidang' => 'Bidang Keperawatan & Kebidanan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Keperawatan Dan Kebidanan', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '390', 'nama_bidang' => 'Ilmu Psikologi', 'parent_category' => 'Ilmu Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '391', 'nama_bidang' => 'Psikologi Umum', 'parent_category' => 'Ilmu Psikologi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '392', 'nama_bidang' => 'Psikologi Anak', 'parent_category' => 'Ilmu Psikologi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '393', 'nama_bidang' => 'Psikologi Masyarakat', 'parent_category' => 'Ilmu Psikologi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '394', 'nama_bidang' => 'Psikologi Kerja (Industri)', 'parent_category' => 'Ilmu Psikologi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '395', 'nama_bidang' => 'Bidang Psikologi Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Psikologi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '400', 'nama_bidang' => 'Ilmu Farmasi', 'parent_category' => 'Ilmu Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '401', 'nama_bidang' => 'Farmasi Umum Dan Apoteker', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '402', 'nama_bidang' => 'Farmakologi Dan Farmasi Klinik', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '403', 'nama_bidang' => 'Biologi Farmasi', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '404', 'nama_bidang' => 'Analisis Farmasi Dan Kimia Medisinal', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '405', 'nama_bidang' => 'Farmasetika Dan Teknologi Farmasi', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '406', 'nama_bidang' => 'Farmasi Makanan Dan Analisis Keamanan Pangan', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '407', 'nama_bidang' => 'Farmasi Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => 'Ilmu Kesehatan'],
            ['kode' => '410', 'nama_bidang' => 'Ilmu Teknik', 'parent_category' => 'Ilmu Farmasi', 'sub_parent_category' => ''],
            ['kode' => '420', 'nama_bidang' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'parent_category' => 'Ilmu Teknik', 'sub_parent_category' => ''],
            ['kode' => '421', 'nama_bidang' => 'Teknik Sipil', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '422', 'nama_bidang' => 'Teknik Lingkungan', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '423', 'nama_bidang' => 'Rancang Kota', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '424', 'nama_bidang' => 'Perencanaan Wilayah Dan Kota', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '425', 'nama_bidang' => 'Teknik Pengairan', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '426', 'nama_bidang' => 'Teknik Arsitektur', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '427', 'nama_bidang' => 'Teknologi Alat Berat', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '428', 'nama_bidang' => 'Transportasi', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '429', 'nama_bidang' => 'Bidang Teknik Sipil Lain Yang Belum Tercantum', 'parent_category' => 'Teknik Sipil Dan Perencanaan Tata Ruang', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '430', 'nama_bidang' => 'Ilmu Keteknikan Industri', 'parent_category' => 'Ilmu Teknik', 'sub_parent_category' => ''],
            ['kode' => '431', 'nama_bidang' => 'Teknik Mesin (Dan Ilmu Permesinan Lain)', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '432', 'nama_bidang' => 'Teknik Produksi (Dan Atau Manufakturing)', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '433', 'nama_bidang' => 'Teknik Kimia', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '434', 'nama_bidang' => 'Teknik (Industri) Farmasi', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '435', 'nama_bidang' => 'Teknik Industri', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '436', 'nama_bidang' => 'Penerbangan/Aeronotika Dan Astronotika', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '437', 'nama_bidang' => 'Teknik Pertekstilan (Tekstil)', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '438', 'nama_bidang' => 'Teknik Refrigerasi', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '439', 'nama_bidang' => 'Bioteknologi Dalam Industri', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '441', 'nama_bidang' => 'Teknik Nuklir (Dan Atau Ilmu Nuklir Lain)', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '442', 'nama_bidang' => 'Teknik Fisika', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '443', 'nama_bidang' => 'Teknik Enerji', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '444', 'nama_bidang' => 'Penginderaan Jauh', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '445', 'nama_bidang' => 'Teknik Material (Ilmu Bahan)', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '446', 'nama_bidang' => 'Bidang Keteknikan Industri Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Keteknikan Industri', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '450', 'nama_bidang' => 'Teknik Elektro Dan Informatika', 'parent_category' => 'Ilmu Teknik', 'sub_parent_category' => ''],
            ['kode' => '451', 'nama_bidang' => 'Teknik Elektro', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '452', 'nama_bidang' => 'Teknik Tenaga Elektrik', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '453', 'nama_bidang' => 'Teknik Telekomunikasi', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '454', 'nama_bidang' => 'Teknik Elektronika', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '455', 'nama_bidang' => 'Teknik Kendali (Atau Instrumentasi Dan Kontrol)', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '456', 'nama_bidang' => 'Teknik Biomedika', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '457', 'nama_bidang' => 'Teknik Komputer', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '458', 'nama_bidang' => 'Teknik Informatika', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '459', 'nama_bidang' => 'Ilmu Komputer', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '461', 'nama_bidang' => 'Sistem Informasi', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '462', 'nama_bidang' => 'Teknologi Informasi', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '463', 'nama_bidang' => 'Teknik Perangkat Lunak', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '464', 'nama_bidang' => 'Teknik Mekatronika', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '465', 'nama_bidang' => 'Bidang Teknik Elektro Dan Informatika Lain Yang Belum Tercantum', 'parent_category' => 'Teknik Elektro Dan Informatika', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '470', 'nama_bidang' => 'Teknologi Kebumian', 'parent_category' => 'Ilmu Teknik', 'sub_parent_category' => ''],
            ['kode' => '471', 'nama_bidang' => 'Teknik Panas Bumi', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '472', 'nama_bidang' => 'Teknik Geofisika', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '473', 'nama_bidang' => 'Teknik Pertambangan (Rekayasa Pertambangan)', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '474', 'nama_bidang' => 'Teknik Perminyakan (Perminyakan)', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '475', 'nama_bidang' => 'Teknik Geologi', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '476', 'nama_bidang' => 'Teknik Geodesi', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '477', 'nama_bidang' => 'Teknik Geomatika', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '478', 'nama_bidang' => 'Bidang Teknologi Kebumian Lain Yang Belum Tercantum', 'parent_category' => 'Teknologi Kebumian', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '480', 'nama_bidang' => 'Ilmu Perkapalan', 'parent_category' => 'Ilmu Teknik', 'sub_parent_category' => ''],
            ['kode' => '481', 'nama_bidang' => 'Teknik Perkapalan', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '482', 'nama_bidang' => 'Teknik Permesinan Kapal', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '483', 'nama_bidang' => 'Teknik Sistem Perkapalan', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '484', 'nama_bidang' => 'Teknik Kelautan Dan Ilmu Kelautan', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '485', 'nama_bidang' => 'Oceanograpi (Oceanologi)', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '486', 'nama_bidang' => 'Bidang Perkapalan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => 'Ilmu Teknik'],
            ['kode' => '500', 'nama_bidang' => 'Ilmu Bahasa', 'parent_category' => 'Ilmu Perkapalan', 'sub_parent_category' => ''],
            ['kode' => '510', 'nama_bidang' => 'Sub Rmpun Ilmu Sastra (Dan Bahasa) Indonesia Dan Daerah', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => ''],
            ['kode' => '511', 'nama_bidang' => 'Sastra (Dan Bahasa) Daerah (Jawa, Sunda, Batak Dll)', 'parent_category' => 'Sub Rmpun Ilmu Sastra (Dan Bahasa) Indonesia Dan Daerah', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '512', 'nama_bidang' => 'Sastra (Dan Bahasa) Indonesia', 'parent_category' => 'Sub Rmpun Ilmu Sastra (Dan Bahasa) Indonesia Dan Daerah', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '513', 'nama_bidang' => 'Sastra (Dan Bahasa) Indonesia Atau Daerah Lainnya', 'parent_category' => 'Sub Rmpun Ilmu Sastra (Dan Bahasa) Indonesia Dan Daerah', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '520', 'nama_bidang' => 'Ilmu Bahasa', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => ''],
            ['kode' => '521', 'nama_bidang' => 'Ilmu Linguistik', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '522', 'nama_bidang' => 'Jurnalistik', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '523', 'nama_bidang' => 'Ilmu Susastra Umum', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '524', 'nama_bidang' => 'Kearsipan', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '525', 'nama_bidang' => 'Ilmu Perpustakaan', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '526', 'nama_bidang' => 'Bidang Ilmu Bahasa Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '530', 'nama_bidang' => 'Ilmu Bahasa Asing', 'parent_category' => 'Ilmu Bahasa', 'sub_parent_category' => ''],
            ['kode' => '531', 'nama_bidang' => 'Sastra (Dan Bahasa) Inggris', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '532', 'nama_bidang' => 'Sastra (Dan Bahasa) Jepang', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '533', 'nama_bidang' => 'Sastra (Dan Bahasa) China (Mandarin)', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '534', 'nama_bidang' => 'Sastra (Dan Bahasa) Arab', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '535', 'nama_bidang' => 'Sastra (Dan Bahasa) Korea', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '536', 'nama_bidang' => 'Sastra (Dan Bahasa) Jerman', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '537', 'nama_bidang' => 'Sastra (Dan Bahasa) Melayu', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '538', 'nama_bidang' => 'Sastra (Dan Bahasa) Belanda', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '539', 'nama_bidang' => 'Sastra (Dan Bahasa) Perancis', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '541', 'nama_bidang' => 'Bidang Sastra (Dan Bahasa) Asing Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => 'Ilmu Bahasa'],
            ['kode' => '550', 'nama_bidang' => 'Ilmu Ekonomi', 'parent_category' => 'Ilmu Bahasa Asing', 'sub_parent_category' => ''],
            ['kode' => '560', 'nama_bidang' => 'Ilmu Ekonomi', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => ''],
            ['kode' => '561', 'nama_bidang' => 'Ekonomi Pembangunan', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '562', 'nama_bidang' => 'Akuntansi', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '563', 'nama_bidang' => 'Ekonomi Syariah', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '564', 'nama_bidang' => 'Perbankan', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '565', 'nama_bidang' => 'Perpajakan', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '566', 'nama_bidang' => 'Asuransi Niaga (Kerugian)', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '567', 'nama_bidang' => 'Notariat', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '568', 'nama_bidang' => 'Bidang Ekonomi Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '570', 'nama_bidang' => 'Ilmu Manajemen', 'parent_category' => 'Ilmu Ekonomi', 'sub_parent_category' => ''],
            ['kode' => '571', 'nama_bidang' => 'Manajemen', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '572', 'nama_bidang' => 'Manajemen Syariah', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '573', 'nama_bidang' => 'Administrasi Keuangan (Perkantoran, Pajak, Hotel, Logistik, Dll)', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '574', 'nama_bidang' => 'Pemasaran', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '575', 'nama_bidang' => 'Manajemen Transportasi', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '576', 'nama_bidang' => 'Manajemen Industri', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '577', 'nama_bidang' => 'Manajemen Informatika', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '578', 'nama_bidang' => 'Kesekretariatan', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '579', 'nama_bidang' => 'Bidang Manajemen Yang Belum Tercantum', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => 'Ilmu Ekonomi'],
            ['kode' => '580', 'nama_bidang' => 'Ilmu Sosial Humaniora', 'parent_category' => 'Ilmu Manajemen', 'sub_parent_category' => ''],
            ['kode' => '590', 'nama_bidang' => 'Ilmu Politik', 'parent_category' => 'Ilmu Sosial Humaniora', 'sub_parent_category' => ''],
            ['kode' => '591', 'nama_bidang' => 'Ilmu Politik', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '592', 'nama_bidang' => 'Kriminologi', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '593', 'nama_bidang' => 'Hubungan Internasional', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '594', 'nama_bidang' => 'Ilmu Administrasi (Niaga, Negara, Publik, Pembangunan, Dll)', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '595', 'nama_bidang' => 'Kriminologi', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '596', 'nama_bidang' => 'Ilmu Hukum', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '597', 'nama_bidang' => 'Ilmu Pemerintahan', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '601', 'nama_bidang' => 'Ilmu Sosial Dan Politik', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '602', 'nama_bidang' => 'Studi Pembangunan (Perencanaan Pembangunan, Wilayah, Kota)', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '603', 'nama_bidang' => 'Ketahanan Nasional', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '604', 'nama_bidang' => 'Ilmu Kepolisian', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '605', 'nama_bidang' => 'Kebijakan Publik', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '606', 'nama_bidang' => 'Bidang Ilmu Politik Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Politik', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '610', 'nama_bidang' => 'Ilmu Sosial', 'parent_category' => 'Ilmu Sosial Humaniora', 'sub_parent_category' => ''],
            ['kode' => '611', 'nama_bidang' => 'Ilmu Kesejahteraan Sosial', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '612', 'nama_bidang' => 'Sosiologi', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '613', 'nama_bidang' => 'Humaniora', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '614', 'nama_bidang' => 'Kajian Wilayah (Eropa, Asia, Jepang, Timur Tengah Dll)', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '615', 'nama_bidang' => 'Arkeologi', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '616', 'nama_bidang' => 'Ilmu Sosiatri', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '617', 'nama_bidang' => 'Kependudukan (Demografi, Dan Ilmu Kependudukan Lain)', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '618', 'nama_bidang' => 'Sejarah (Ilmu Sejarah)', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '619', 'nama_bidang' => 'Kajian Budaya', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '621', 'nama_bidang' => 'Komunikasi Penyiaran Islam', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '622', 'nama_bidang' => 'Ilmu Komunikasi', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '623', 'nama_bidang' => 'Antropologi', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '624', 'nama_bidang' => 'Bidang Sosial Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => 'Ilmu Sosial Humaniora'],
            ['kode' => '630', 'nama_bidang' => 'Agama Dan Filsafat', 'parent_category' => 'Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '640', 'nama_bidang' => 'Ilmu Pengetahuan (Ilmu) Agama', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '641', 'nama_bidang' => 'Agama Islam', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '642', 'nama_bidang' => 'Agama Katolik', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '643', 'nama_bidang' => 'Agama Kristen Dan Teologia', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '644', 'nama_bidang' => 'Sosiologi Agama', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '645', 'nama_bidang' => 'Agama (Filsafat) Hindu, Budha, Dan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '650', 'nama_bidang' => 'Ilmu Filsafat', 'parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama', 'sub_parent_category' => ''],
            ['kode' => '651', 'nama_bidang' => 'Filsafat', 'parent_category' => 'Ilmu Filsafat', 'sub_parent_category' => 'Ilmu Pengetahuan (Ilmu) Agama'],
              ['kode' => '652', 'nama_bidang' => 'Ilmu Religi Dan Budaya', 'parent_category' => 'Ilmu Filsafat', 'sub_parent_category' => ''],
            ['kode' => '653', 'nama_bidang' => 'Filsafat Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Filsafat', 'sub_parent_category' => ''],
            ['kode' => '660', 'nama_bidang' => 'Ilmu Seni, Desain Dan Media', 'parent_category' => 'Ilmu Filsafat', 'sub_parent_category' => ''],
            ['kode' => '670', 'nama_bidang' => 'Ilmu Seni Pertunjukan', 'parent_category' => 'Ilmu Seni, Desain Dan Media', 'sub_parent_category' => ''],
            ['kode' => '671', 'nama_bidang' => 'Senitari', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '672', 'nama_bidang' => 'Seni Teater', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '673', 'nama_bidang' => 'Seni Pedalangan', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '674', 'nama_bidang' => 'Seni Musik', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '675', 'nama_bidang' => 'Seni Karawitan', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '676', 'nama_bidang' => 'Seni Pertunjukkan Lainnya Yang Belum Disebut', 'parent_category' => 'Ilmu Seni Pertunjukan', 'sub_parent_category' => ''],
            ['kode' => '680', 'nama_bidang' => 'Ilmu Kesenian', 'parent_category' => 'Ilmu Seni, Desain Dan Media', 'sub_parent_category' => ''],
            ['kode' => '681', 'nama_bidang' => 'Penciptaan Seni', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '682', 'nama_bidang' => 'Etnomusikologi', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '683', 'nama_bidang' => 'Antropologi Tari', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '684', 'nama_bidang' => 'Seni Rupa Murni (Seni Lukis)', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '685', 'nama_bidang' => 'Seni Patung', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '687', 'nama_bidang' => 'Seni Grafis', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '688', 'nama_bidang' => 'Seni Intermedia', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '689', 'nama_bidang' => 'Bidang Ilmu Kesenian Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Kesenian', 'sub_parent_category' => ''],
            ['kode' => '690', 'nama_bidang' => 'Ilmu Seni Kriya', 'parent_category' => 'Ilmu Seni, Desain Dan Media', 'sub_parent_category' => ''],
            ['kode' => '691', 'nama_bidang' => 'Kriya Patung', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '692', 'nama_bidang' => 'Kriya Kayu', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '693', 'nama_bidang' => 'Kriya Kulit', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '694', 'nama_bidang' => 'Kriya Keramik', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '695', 'nama_bidang' => 'Kriya Tekstil', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '696', 'nama_bidang' => 'Kriya Logam (Dan Logam Mulia/Perhiasan)', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '697', 'nama_bidang' => 'Bidang Seni Kriya Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '699', 'nama_bidang' => 'Kepariwisataan', 'parent_category' => 'Ilmu Seni Kriya', 'sub_parent_category' => ''],
            ['kode' => '700', 'nama_bidang' => 'Ilmu Media', 'parent_category' => 'Ilmu Seni, Desain Dan Media', 'sub_parent_category' => ''],
            ['kode' => '701', 'nama_bidang' => 'Fotografi', 'parent_category' => 'Ilmu Media', 'sub_parent_category' => ''],
            ['kode' => '702', 'nama_bidang' => 'Televisi', 'parent_category' => 'Ilmu Media', 'sub_parent_category' => ''],
            ['kode' => '703', 'nama_bidang' => 'Broadcasting (Penyiaran)', 'parent_category' => 'Ilmu Media', 'sub_parent_category' => ''],
            ['kode' => '704', 'nama_bidang' => 'Grafika (Dan Penerbitan)', 'parent_category' => 'Ilmu Media', 'sub_parent_category' => ''],
            ['kode' => '705', 'nama_bidang' => 'Bidang Media Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Media', 'sub_parent_category' => ''],
            ['kode' => '706', 'nama_bidang' => 'Desain', 'parent_category' => 'Ilmu Seni, Desain Dan Media', 'sub_parent_category' => ''],
            ['kode' => '707', 'nama_bidang' => 'Desain Interior', 'parent_category' => 'Desain', 'sub_parent_category' => ''],
            ['kode' => '708', 'nama_bidang' => 'Desain Komunikasi Visual', 'parent_category' => 'Desain', 'sub_parent_category' => ''],
            ['kode' => '709', 'nama_bidang' => 'Desain Produk', 'parent_category' => 'Desain', 'sub_parent_category' => ''],
            ['kode' => '710', 'nama_bidang' => 'Ilmu Pendidikan', 'parent_category' => 'Desain', 'sub_parent_category' => ''],
            ['kode' => '720', 'nama_bidang' => 'Pendidikan Ilmu Sosial', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '721', 'nama_bidang' => 'Pendidikan Pancasila Dan Kewarganegaraan', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '722', 'nama_bidang' => 'Pendidikan Sejarah', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '723', 'nama_bidang' => 'Pendidikan Ekonomi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '724', 'nama_bidang' => 'Pendidikan Geografi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '725', 'nama_bidang' => 'Pendidikan Sosiologi Dan Antropologi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '726', 'nama_bidang' => 'Pendidikan Akuntansi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '727', 'nama_bidang' => 'Pendidikan Tata Niaga', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '728', 'nama_bidang' => 'Pendidikan Administrasi Perkantoran', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '729', 'nama_bidang' => 'Pendidikan Bahasa Jepang', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '731', 'nama_bidang' => 'Pendidikan Sosiologi (Ilmu Sosial)', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '732', 'nama_bidang' => 'Pendidikan Koperasi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '733', 'nama_bidang' => 'Pend Kependudukan Dan Lingkungan Hidup', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '734', 'nama_bidang' => 'Pendidikan Ekonomi Koperasi', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '735', 'nama_bidang' => 'Bidang Pendidikan Ilmu Sosial Lain Yang Belum Tercantum', 'parent_category' => 'Pendidikan Ilmu Sosial', 'sub_parent_category' => ''],
            ['kode' => '740', 'nama_bidang' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '741', 'nama_bidang' => 'Pendidikan Bahasa, Sastra Indonesia Dan Daerah', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '742', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Inggris', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '743', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Indonesia', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '744', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Jerman', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '745', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Perancis', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '746', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Arab', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '747', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Perancis', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '748', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Jawa', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '749', 'nama_bidang' => 'Pendidikan Bahasa (Dan Sastra) Cina (Mandarin)', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '751', 'nama_bidang' => 'Bidang Pendidikan Bahasa (Dan Satra) Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan Bahasa Dan Sastra', 'sub_parent_category' => ''],
            ['kode' => '760', 'nama_bidang' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '761', 'nama_bidang' => 'Pendidikan Jasmani, Kesehatan Dan Rekreasi', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '762', 'nama_bidang' => 'Pendidikan Jasmani Dan Kesehatan', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '763', 'nama_bidang' => 'Pendidikan Olahraga Dan Kesehatan', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '764', 'nama_bidang' => 'Pendidikan Kepelatihan Olahraga', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '765', 'nama_bidang' => 'Ilmu Keolahragaan', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '766', 'nama_bidang' => 'Pendidikan Olah Raga Dan Kesehatan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan Olah Raga Dan Kesehatan', 'sub_parent_category' => ''],
            ['kode' => '770', 'nama_bidang' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '771', 'nama_bidang' => 'Pendidikan Biologi', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '772', 'nama_bidang' => 'Pendidikan Matematika', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '773', 'nama_bidang' => 'Pendidikan Fisika', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '774', 'nama_bidang' => 'Pendidikan Kimia', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '775', 'nama_bidang' => 'Pendidikan Ilmu Pengetahuan Alam (Sains)', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '776', 'nama_bidang' => 'Pendidikan Geografi', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '777', 'nama_bidang' => 'Pendidikan Mipa Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan Matematika Dan Ilmu Pengetahuan Alam (Mipa)', 'sub_parent_category' => ''],
            ['kode' => '780', 'nama_bidang' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '781', 'nama_bidang' => 'Pendidikan Teknik Mesin', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '782', 'nama_bidang' => 'Pendidikan Teknik Bangunan', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '783', 'nama_bidang' => 'Pendidikan Teknik Elektro', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '784', 'nama_bidang' => 'Pendidikan Teknik Elektronika', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '785', 'nama_bidang' => 'Pendidikan Teknik Otomotif', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '786', 'nama_bidang' => 'Pendidikan Teknik Informatika', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '787', 'nama_bidang' => 'Pendidikan Kesejahteraan Keluarga (Tataboga, Busana, Rias Dll)', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '788', 'nama_bidang' => 'Pend. Teknologi Dan Kejuruan', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '789', 'nama_bidang' => 'Bidang Pend. Teknologi Dan Kejuruan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan Teknologi Dan Kejuruan', 'sub_parent_category' => ''],
            ['kode' => '790', 'nama_bidang' => 'Ilmu Pendidikan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '791', 'nama_bidang' => 'Pendidikan Luar Biasa', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '792', 'nama_bidang' => 'Pendidikan Luar Sekolah', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '793', 'nama_bidang' => 'Pgsd', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '794', 'nama_bidang' => 'Pgtk Dan (Paud)', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '795', 'nama_bidang' => 'Psikologi Pendidikan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '796', 'nama_bidang' => 'Pengukuran Dan Evaluasi Pendidikan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '797', 'nama_bidang' => 'Pengembangan Kurikulum', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '798', 'nama_bidang' => 'Teknologi Pendidikan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '799', 'nama_bidang' => 'Administrasi Pendidikan (Manajemen Pendidikan)', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '801', 'nama_bidang' => 'Pendidikan Anak Usia Dini', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '802', 'nama_bidang' => 'Kurikulum Dan Teknologi Pendidikan', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '803', 'nama_bidang' => 'Bimbingan Dan Konseling', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '804', 'nama_bidang' => 'Bidang Pendidikan Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '810', 'nama_bidang' => 'Ilmu Pendidikan Kesenian', 'parent_category' => 'Ilmu Pendidikan', 'sub_parent_category' => ''],
            ['kode' => '811', 'nama_bidang' => 'Pendidikan Seni Drama, Tari Dan Musik', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '812', 'nama_bidang' => 'Pendidikan Seni Rupa', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '813', 'nama_bidang' => 'Pendidikan Seni Musik', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '814', 'nama_bidang' => 'Pendidikan Seni Tari', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '815', 'nama_bidang' => 'Pendidikan Keterampilan Dan Kerajinan', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '816', 'nama_bidang' => 'Pendidikan Seni Kerajinan', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '817', 'nama_bidang' => 'Bidang Pendidikan Kesenian Lain Yang Belum Tercantum', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '900', 'nama_bidang' => 'Rumpun Ilmu Lainnya', 'parent_category' => 'Ilmu Pendidikan Kesenian', 'sub_parent_category' => ''],
            ['kode' => '647', 'nama_bidang' => 'Agama Hindu', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '3400', 'nama_bidang' => 'Ilmu atau Sains Lingkungan', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '99', 'nama_bidang' => '*', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '620', 'nama_bidang' => 'Ilmu Humaniora', 'parent_category' => '', 'sub_parent_category' => ''],
            ['kode' => '625', 'nama_bidang' => 'Hubungan Masyarakat', 'parent_category' => 'Ilmu Humaniora', 'sub_parent_category' => ''],
            ['kode' => '626', 'nama_bidang' => 'Periklanan', 'parent_category' => 'Ilmu Humaniora', 'sub_parent_category' => ''],
            ['kode' => '627', 'nama_bidang' => 'Televisi dan Film', 'parent_category' => 'Ilmu Humaniora', 'sub_parent_category' => ''],
            ['kode' => '628', 'nama_bidang' => 'Manajemen Komunikasi dan Media', 'parent_category' => 'Ilmu Humaniora', 'sub_parent_category' => ''],
            ['kode' => '629', 'nama_bidang' => 'Bidang Humaniora lain yang belum tercantum', 'parent_category' => 'Ilmu Humaniora', 'sub_parent_category' => ''],
            ['kode' => '646', 'nama_bidang' => 'Agama Budha', 'parent_category' => '', 'sub_parent_category' => ''],
        ];

        // Insert data
        foreach ($data as $item) {
            DB::table('simpeg_rumpun_bidang_ilmu')->insert([
                'kode' => $item['kode'],
                'nama_bidang' => $item['nama_bidang'],
                'parent_category' => $item['parent_category'],
                'sub_parent_category' => $item['sub_parent_category'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}