<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class SimpegMasterGelarAkademikSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $gelarData = [
            ['gelar' => 'S.S.', 'nama_gelar' => 'Sarjana Sastra'],
            ['gelar' => 'S.H.', 'nama_gelar' => 'Sarjana Hukum'],
            ['gelar' => 'S.E.', 'nama_gelar' => 'Sarjana Ekonomi'],
            ['gelar' => 'S.IP', 'nama_gelar' => 'Sarjana Ilmu Politik'],
            ['gelar' => 'S.Sos', 'nama_gelar' => 'Sarjana Ilmu Sosial'],
            ['gelar' => 'S.Psi', 'nama_gelar' => 'Sarjana Psikologi'],
            ['gelar' => 'S.Ked', 'nama_gelar' => 'Sarjana Kedokteran'],
            ['gelar' => 'S.KM', 'nama_gelar' => 'Sarjana Kesehatan Masyarakat'],
            ['gelar' => 'S.KG', 'nama_gelar' => 'Sarjana Kedokteran Gigi'],
            ['gelar' => 'S.P', 'nama_gelar' => 'Sarjana Pertanian'],
            ['gelar' => 'S.TP', 'nama_gelar' => 'Sarjana Teknologi Pertanian'],
            ['gelar' => 'S.Pt', 'nama_gelar' => 'Sarjana Peternakan'],
            ['gelar' => 'S.Pi', 'nama_gelar' => 'Sarjana Perikanan'],
            ['gelar' => 'S.Hut', 'nama_gelar' => 'Sarjana Kehutanan'],
            ['gelar' => 'S.KH', 'nama_gelar' => 'Sarjana Kedokteran Hewan'],
            ['gelar' => 'S.Si', 'nama_gelar' => 'Sarjana Sains'],
            ['gelar' => 'S.T', 'nama_gelar' => 'Sarjana Teknik'],
            ['gelar' => 'S.Kom', 'nama_gelar' => 'Sarjana Komputer'],
            ['gelar' => 'S.Sn', 'nama_gelar' => 'Sarjana Seni'],
            ['gelar' => 'S.Pd', 'nama_gelar' => 'Sarjana Pendidikan'],
            ['gelar' => 'S.Ag', 'nama_gelar' => 'Sarjana Agama'],
            ['gelar' => 'M.Hum', 'nama_gelar' => 'Magister Humaniora'],
            ['gelar' => 'M.M.', 'nama_gelar' => 'Magister Manajemen'],
            ['gelar' => 'M.Si', 'nama_gelar' => 'Magister Sains'],
            ['gelar' => 'M.Kes', 'nama_gelar' => 'Magister Kesehatan'],
            ['gelar' => 'M.P', 'nama_gelar' => 'Magister Pertanian'],
            ['gelar' => 'M.T', 'nama_gelar' => 'Magister Teknik'],
            ['gelar' => 'M.Kom', 'nama_gelar' => 'Magister Komputer'],
            ['gelar' => 'M.Sn', 'nama_gelar' => 'Magister Seni'],
            ['gelar' => 'M.Pd', 'nama_gelar' => 'Magister Pendidikan'],
            ['gelar' => 'M.Ag', 'nama_gelar' => 'Magister Agama'],
            ['gelar' => 'Drs', 'nama_gelar' => 'Doktorandus'],
            ['gelar' => 'Dra', 'nama_gelar' => 'Doktoranda'],
            ['gelar' => 'Ir', 'nama_gelar' => 'Insinyur'],
            ['gelar' => 'Dr', 'nama_gelar' => 'Doktor'],
            ['gelar' => 'Prof', 'nama_gelar' => 'Profesor'],
            ['gelar' => 'Ph.D', 'nama_gelar' => 'Doctor of Philosophy'],
            ['gelar' => 'M.M.Pd', 'nama_gelar' => 'Magister Manajemen Pendidikan'],
            ['gelar' => 'S.Mn', 'nama_gelar' => 'Sarjana Manajemen'],
            ['gelar' => 'S.Pd.I', 'nama_gelar' => 'Sarjana Pendidikan Islam'],
            ['gelar' => 'S.Pd.Kom', 'nama_gelar' => 'Sarjana Pendidikan Komputer'],
            ['gelar' => 'S.Sy', 'nama_gelar' => 'Sarjana Syariah'],
            ['gelar' => 'S.Sos.I', 'nama_gelar' => 'Sarjana Sosial Islam'],
            ['gelar' => 'S.Th.I', 'nama_gelar' => 'Sarjana Theologi Islam'],
            ['gelar' => 'S.Pil.I', 'nama_gelar' => 'Sarjana Pilosophi Islam'],
            ['gelar' => 'S.Hum', 'nama_gelar' => 'Sarjana Humaniora'],
            ['gelar' => 'A.Md', 'nama_gelar' => 'Ahli Madya'],
            ['gelar' => 'A.Ma.Pd', 'nama_gelar' => 'Ahli Madya Pendidikan'],
            ['gelar' => 'B.A.', 'nama_gelar' => 'Bachelor of Art'],
            ['gelar' => 'Dipl.-Ing.', 'nama_gelar' => 'Diplom-Ingenieur'],
            ['gelar' => 'S.ST', 'nama_gelar' => 'Sarjana Sains Terapan'],
            ['gelar' => 'S.Kep', 'nama_gelar' => 'Sarjana Keperawatan'],
            ['gelar' => 'M.Kep', 'nama_gelar' => 'Magister Keperawatan'],
            ['gelar' => 'M.MKes', 'nama_gelar' => 'Magister Manajemen Kesehatan'],
            ['gelar' => 'M.P.h', 'nama_gelar' => 'Magister Public Hotel'],
            ['gelar' => 'A.Per.Pen', 'nama_gelar' => 'Ahli Perawat Pendidik'],
            ['gelar' => 'M.E', 'nama_gelar' => 'Magister Ekonomi'],
            ['gelar' => 'M.Sos', 'nama_gelar' => 'Magister Sosial'],
            ['gelar' => 'A.Md.Si', 'nama_gelar' => 'Ahli Madya Sains'],
            ['gelar' => 'A.Md.Kom', 'nama_gelar' => 'Ahli Madya Komputer'],
            ['gelar' => 'S.Mat', 'nama_gelar' => 'Sarjana Matematika'],
            ['gelar' => 'M.Mat', 'nama_gelar' => 'Magister Matematika'],
            ['gelar' => 'S.Stat', 'nama_gelar' => 'Sarjana Statistika'],
            ['gelar' => 'M.Stat', 'nama_gelar' => 'Magister Statistika'],
            ['gelar' => 'A.Md.Pt', 'nama_gelar' => 'Ahli Madya Peternakan'],
            ['gelar' => 'M.Pt', 'nama_gelar' => 'Magister Peternakan'],
            ['gelar' => 'M.Pi', 'nama_gelar' => 'Magister Perikanan'],
            ['gelar' => 'A.Md.Pi', 'nama_gelar' => 'Ahli Madya Perikanan'],
            ['gelar' => 'S.Agr', 'nama_gelar' => 'Sarjana Agraria'],
            ['gelar' => 'M.Agr', 'nama_gelar' => 'Magister Agraria'],
            ['gelar' => 'M.P.W', 'nama_gelar' => 'Magister Perencanaan Wilayah'],
            ['gelar' => 'S.Ars', 'nama_gelar' => 'Sarjana Arsitektur'],
            ['gelar' => 'M.Ars', 'nama_gelar' => 'Magister Arsitektur'],
            ['gelar' => 'A.Md.Akun', 'nama_gelar' => 'Ahli Madya Akuntansi'],
            ['gelar' => 'S.M', 'nama_gelar' => 'Sarjana Manajemen'],
            ['gelar' => 'M.M', 'nama_gelar' => 'Magister Manajemen'],
            ['gelar' => 'A.Md.T', 'nama_gelar' => 'Ahli Madya Teknik'],
            ['gelar' => 'M.Ling', 'nama_gelar' => 'Magister Linguistik'],
            ['gelar' => 'M.Gz', 'nama_gelar' => 'Magister Gizi'],
            ['gelar' => 'M.Vet', 'nama_gelar' => 'Magister Veteriner'],
            ['gelar' => 'S.K.H', 'nama_gelar' => 'Sarjana Kedokteran Hewan'],
            ['gelar' => 'drh.', 'nama_gelar' => 'Dokter Hewan'],
            ['gelar' => 'S.Gz', 'nama_gelar' => 'Sarjana Gizi'],
            ['gelar' => 'M.I.K', 'nama_gelar' => 'Magister Ilmu Komputer'],
            ['gelar' => 'M.Bitek', 'nama_gelar' => 'Magister Bioteknologi'],
            ['gelar' => 'S.Ds', 'nama_gelar' => 'Sarjana Desain'],
            ['gelar' => 'S.Tr.Ds', 'nama_gelar' => 'Sarjana Terapan Desain'],
            ['gelar' => 'M.Akt', 'nama_gelar' => 'Magister Akuntansi'],
            ['gelar' => 'S.P.W', 'nama_gelar' => 'Sarjana Perencanaan Wilayah'],
            ['gelar' => 'M.Log', 'nama_gelar' => 'Magister Logistik'],
            ['gelar' => 'M.A.B', 'nama_gelar' => 'Magister Agribisnis'],
            ['gelar' => 'S.Bns', 'nama_gelar' => 'Sarjana Bisnis'],
            ['gelar' => 'M.Farm', 'nama_gelar' => 'Magister Farmasi'],
            ['gelar' => 'S.Farm', 'nama_gelar' => 'Sarjana Farmasi'],
            ['gelar' => 'Apt', 'nama_gelar' => 'Apoteker'],
            ['gelar' => 'S.Bitek', 'nama_gelar' => 'Sarjana Bioteknologi'],
            ['gelar' => 'S.Tr.M', 'nama_gelar' => 'Sarjana Terapan Manajemen'],
            ['gelar' => 'Guru', 'nama_gelar' => 'Guru'],
            ['gelar' => 'A.Md.Js', 'nama_gelar' => 'Ahli Madya Jasa'],
            ['gelar' => 'S.Or', 'nama_gelar' => 'Sarjana Olahraga'],
            ['gelar' => 'Kr', 'nama_gelar' => 'Koreografer'],
            ['gelar' => 'A.Md.A.P', 'nama_gelar' => 'Ahli Madya Administrasi Perkantoran'],
            ['gelar' => 'M.Or', 'nama_gelar' => 'Magister Olahraga'],
            ['gelar' => 'Sp.Rad.O.M', 'nama_gelar' => 'Spesialis Radiologi Oral dan Maksilofasial'],
            ['gelar' => 'Sp.K.N', 'nama_gelar' => 'Spesialis Kedokteran Nuklir'],
            ['gelar' => 'A.Md.Pd', 'nama_gelar' => 'Ahli Madya Pendidikan'],
            ['gelar' => 'M.Ked', 'nama_gelar' => 'Magister Kedokteran'],
            ['gelar' => 'A.Md.Farm', 'nama_gelar' => 'Ahli Madya Farmasi'],
            ['gelar' => 'S.Tr.Ptk', 'nama_gelar' => 'Sarjana Terapan Peternakan'],
            ['gelar' => 'M.Ds', 'nama_gelar' => 'Magister Desain'],
            ['gelar' => 'M.Js', 'nama_gelar' => 'Magister Jasa'],
            ['gelar' => 'A.Md.Sn', 'nama_gelar' => 'Ahli Madya Seni'],
            ['gelar' => 'A.Md.T.W', 'nama_gelar' => 'Ahli Madya Tata Wisata'],
            ['gelar' => 'S.Tr.I.K', 'nama_gelar' => 'Sarjana Terapan Ilmu Komputer'],
            ['gelar' => 'S.Tr.Tra', 'nama_gelar' => 'Sarjana Terapan Transportasi'],
            ['gelar' => 'A.Md.Akt', 'nama_gelar' => 'Ahli Madya Aktuaria'],
            ['gelar' => 'A.Md.Log', 'nama_gelar' => 'Ahli Madya Logistik'],
            ['gelar' => 'M.Tra', 'nama_gelar' => 'Magister Transportasi'],
            ['gelar' => 'S.Tr.Kom', 'nama_gelar' => 'Sarjana Terapan Komputer'],
            ['gelar' => 'A.Md.Gz', 'nama_gelar' => 'Ahli Madya Gizi'],
            ['gelar' => 'A.P.Kes', 'nama_gelar' => 'Ahli Pertama Kesehatan'],
            ['gelar' => 'A.Md.Sos', 'nama_gelar' => 'Ahli Madya Sosial'],
            ['gelar' => 'M.S.M', 'nama_gelar' => 'Master Sains Manajemen'],
            ['gelar' => 'M.Keb', 'nama_gelar' => 'Magister Kebidanan'],
            ['gelar' => 'MH.Kes', 'nama_gelar' => 'Magister Kesehatan'],
            ['gelar' => 'M.MT', 'nama_gelar' => 'Magister Manajemen Teknologi'],
            ['gelar' => 'M.Ec.Dev', 'nama_gelar' => 'Master of Economic of Development'],
            ['gelar' => 'M.AAC', 'nama_gelar' => 'Master in Accounting and Controlling'],
            ['gelar' => 'M.ACC', 'nama_gelar' => 'Master in Accounting and Controlling'],
            ['gelar' => 'M.Acc', 'nama_gelar' => 'Master of Accounting'],
            ['gelar' => 'S.Th', 'nama_gelar' => 'Sarjana Theologi'],
            ['gelar' => 'M.Th', 'nama_gelar' => 'Magister Theologi'],
            ['gelar' => 'D.Th', 'nama_gelar' => 'Doktor Theologi'],
            ['gelar' => 'M.KM', 'nama_gelar' => 'Magister Kesehatan Masyarakat'],
            ['gelar' => 'M.Fis', 'nama_gelar' => 'Magister Fisioterapi'],
            ['gelar' => 'M.Cs', 'nama_gelar' => 'Master of Computer Science'],
            ['gelar' => 'M.Sc.E.', 'nama_gelar' => 'Master of Science in Economics'],
            ['gelar' => 'M.Sc.A.', 'nama_gelar' => 'Master of Science in Accounting'],
            ['gelar' => 'M.Sc.M.', 'nama_gelar' => 'Master of Science in Management'],
            ['gelar' => 'M.Sc.P.', 'nama_gelar' => 'Master of Science in Pharmacy'],
            ['gelar' => 'LL.M', 'nama_gelar' => 'Master of Laws'],
            ['gelar' => 'M.Kn.', 'nama_gelar' => 'Magister Kenotariatan'],
            ['gelar' => 'MPA', 'nama_gelar' => 'Master of Public Administration'],
            ['gelar' => 'M.Biotech', 'nama_gelar' => 'Master of Biotechnology'],
            ['gelar' => 'M. MA', 'nama_gelar' => 'Magister Manajemen Agribisnis'],
            ['gelar' => 'M.Pd.Si', 'nama_gelar' => 'Magister Pendidikan Sains'],
            ['gelar' => 'M.S.Ak', 'nama_gelar' => 'Magister Sains Akuntansi'],
            ['gelar' => 'S.E.I', 'nama_gelar' => 'Sarjana Ekonomi Islam'],
            ['gelar' => 'M.Sas', 'nama_gelar' => 'Magister Sastra'],
            ['gelar' => 'M.M.S.I', 'nama_gelar' => 'Magister Manajemen Sistem Informasi'],
            ['gelar' => 'S.I.Kom', 'nama_gelar' => 'Sarjana Ilmu Komunikasi'],
            ['gelar' => 'M.I.Kom', 'nama_gelar' => 'Magister Ilmu Komunikasi'],
            ['gelar' => 'M.Med.Kom', 'nama_gelar' => 'Magister Media dan Komunikasi'],
            ['gelar' => 'M.Biomed', 'nama_gelar' => 'Magister Biomedik'],
            ['gelar' => 'M.PPO.', 'nama_gelar' => 'M. Perubahan & Pengembangan Organisasi'],
            ['gelar' => 'M.Epid.', 'nama_gelar' => 'Magister Epidemiologi'],
            ['gelar' => 'M.M.Tr.', 'nama_gelar' => 'Magister Manajemen Transporasi'],
            ['gelar' => 'Sp.KK', 'nama_gelar' => 'Spesialis Kesehatan Kulit dan Kelamin'],
            ['gelar' => 'M.Kom.I', 'nama_gelar' => 'Magister Komunikasi Islam'],
            ['gelar' => 'M.T.A', 'nama_gelar' => 'Magister Teknologi Agroindustri'],
            ['gelar' => 'M.Psi', 'nama_gelar' => 'Magister Psikologi'],
            ['gelar' => 'Psikolog.', 'nama_gelar' => 'Psikolog'],
            ['gelar' => 'Sp.BP', 'nama_gelar' => 'Spesialis Bedah Plastik'],
            ['gelar' => 'Sp.F', 'nama_gelar' => 'Spesialis Forensik'],
            ['gelar' => 'Sp.FRS.', 'nama_gelar' => 'Spesialis Farmasi Rumah Sakit'],
            ['gelar' => 'M.Par', 'nama_gelar' => 'Magister Pariwisata'],
            ['gelar' => 'ATD', 'nama_gelar' => 'Ahli Transportasi Darat'],
            ['gelar' => 'M.PSDM', 'nama_gelar' => 'Magister Pengembangan Sumber Daya Manusia'],
            ['gelar' => 'M.S.I', 'nama_gelar' => 'Magister Studi Islam'],
            ['gelar' => 'M.PSDA', 'nama_gelar' => 'Magister Pengelolaan Sumberdaya Air'],
            ['gelar' => 'M.PFis', 'nama_gelar' => 'Magister Pengajaran Fisika'],
            ['gelar' => 'M.Pd.Mat', 'nama_gelar' => 'Magister Pendidikan Matematika'],
            ['gelar' => 'M.I.P', 'nama_gelar' => 'Magister Ilmu Politik'],
            ['gelar' => 'M.S.W', 'nama_gelar' => 'Magister Studi Wanita'],
            ['gelar' => 'M.Imun.', 'nama_gelar' => 'Magister Imunologi'],
            ['gelar' => 'M.SA', 'nama_gelar' => 'Magister Sain Akuntansi'],
            ['gelar' => 'DCN', 'nama_gelar' => 'Diploma in Clinical Nutrition'],
            ['gelar' => 'MKKK', 'nama_gelar' => 'Magister Keselamatan dan Kesehatan Kerja'],
            ['gelar' => 'MMedEd', 'nama_gelar' => 'Master of Medical Education'],
            ['gelar' => 'M.Agb.', 'nama_gelar' => 'Magister Agribisnis'],
            ['gelar' => 'S.ST.Par', 'nama_gelar' => 'Sarjana Sains Terapan Pariwisata'],
            ['gelar' => 'M.M.Tr', 'nama_gelar' => 'Magister Manajemen Transportasi'],
            ['gelar' => 'M.HI', 'nama_gelar' => 'Magister Hukum Islam'],
            ['gelar' => 'M.Th.I', 'nama_gelar' => 'Magister Theologi Islam'],
            ['gelar' => 'Sp.JP', 'nama_gelar' => 'Spesialis Jantung dan Pembuluh Darah'],
            ['gelar' => 'M.M.R.S.', 'nama_gelar' => 'Magister Manajemen Rumah Sakit'],
            ['gelar' => 'M.T.Pd', 'nama_gelar' => 'Magister Teknologi Pendidikan'],
            ['gelar' => 'S.Kel', 'nama_gelar' => 'Sarjana Kelautan'],
            ['gelar' => 'M.E.I', 'nama_gelar' => 'Magister Ekonomi Islam'],
            ['gelar' => 'M.Ked.Trop', 'nama_gelar' => 'Magister Kedokteran Tropis'],
            ['gelar' => 'M.Si.Med', 'nama_gelar' => 'Magister Sains Medicine'],
            ['gelar' => 'MMRS', 'nama_gelar' => 'Magister Manajemen Rumah Sakit'],
            ['gelar' => 'S.Kp', 'nama_gelar' => 'Sarjana Keperawatan'],
            ['gelar' => 'SE.Sy', 'nama_gelar' => 'Sarjana Ekonomi Syariah']
        ];
        
        // Add created_at and updated_at to each record
        $dataToInsert = array_map(function ($item) use ($now) {
            $item['id'] = Str::uuid();
            $item['created_at'] = $now;
            $item['updated_at'] = $now;
            return $item;
        }, $gelarData);
        
        // Insert data in chunks to avoid exceeding max insert size
        foreach (array_chunk($dataToInsert, 100) as $chunk) {
            DB::table('simpeg_master_gelar_akademik')->insert($chunk);
        }
        
        $this->command->info('Successfully seeded simpeg_gelar_akademik table with ' . count($gelarData) . ' records.');
    }
}