<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SimpegJabatanFungsionalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jabatanFungsional = [
            [
                'id' => 1,
                'jabatan_akademik_id' => 1,
                'pangkat_id' => 1,
                'kode' => 'AA',
                'nama_jabatan_fungsional' => 'Asisten Ahli',
                'kode_jabatan_akademik' => 'AA',
                'pangkat' => 'III/a',
                'angka_kredit' => '100',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen pemula',
            ],
            [
                'id' => 2,
                'jabatan_akademik_id' => 1,
                'pangkat_id' => 2,
                'kode' => 'AA1',
                'nama_jabatan_fungsional' => 'Asisten Ahli',
                'kode_jabatan_akademik' => 'AA',
                'pangkat' => 'III/b',
                'angka_kredit' => '150',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen pemula tingkat lanjut',
            ],
            [
                'id' => 3,
                'jabatan_akademik_id' => 2,
                'pangkat_id' => 3,
                'kode' => 'L',
                'nama_jabatan_fungsional' => 'Lektor',
                'kode_jabatan_akademik' => 'L',
                'pangkat' => 'III/c',
                'angka_kredit' => '200',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen madya',
            ],
            [
                'id' => 4,
                'jabatan_akademik_id' => 2,
                'pangkat_id' => 4,
                'kode' => 'L1',
                'nama_jabatan_fungsional' => 'Lektor',
                'kode_jabatan_akademik' => 'L',
                'pangkat' => 'III/d',
                'angka_kredit' => '300',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen madya tingkat lanjut',
            ],
            [
                'id' => 5,
                'jabatan_akademik_id' => 3,
                'pangkat_id' => 5,
                'kode' => 'LK',
                'nama_jabatan_fungsional' => 'Lektor Kepala',
                'kode_jabatan_akademik' => 'LK',
                'pangkat' => 'IV/a',
                'angka_kredit' => '400',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen senior',
            ],
            [
                'id' => 6,
                'jabatan_akademik_id' => 3,
                'pangkat_id' => 6,
                'kode' => 'LK1',
                'nama_jabatan_fungsional' => 'Lektor Kepala',
                'kode_jabatan_akademik' => 'LK',
                'pangkat' => 'IV/b',
                'angka_kredit' => '550',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen senior tingkat lanjut',
            ],
            [
                'id' => 7,
                'jabatan_akademik_id' => 3,
                'pangkat_id' => 7,
                'kode' => 'LK2',
                'nama_jabatan_fungsional' => 'Lektor Kepala',
                'kode_jabatan_akademik' => 'LK',
                'pangkat' => 'IV/c',
                'angka_kredit' => '700',
                'usia_pensiun' => 65,
                'keterangan' => 'Jabatan fungsional dosen senior tingkat utama',
            ],
            [
                'id' => 8,
                'jabatan_akademik_id' => 4,
                'pangkat_id' => 8,
                'kode' => 'GB',
                'nama_jabatan_fungsional' => 'Guru Besar',
                'kode_jabatan_akademik' => 'GB',
                'pangkat' => 'IV/d',
                'angka_kredit' => '850',
                'usia_pensiun' => 70,
                'keterangan' => 'Jabatan fungsional dosen tertinggi',
            ],
            [
                'id' => 9,
                'jabatan_akademik_id' => 4,
                'pangkat_id' => 9,
                'kode' => 'GB1',
                'nama_jabatan_fungsional' => 'Guru Besar',
                'kode_jabatan_akademik' => 'GB',
                'pangkat' => 'IV/e',
                'angka_kredit' => '1050',
                'usia_pensiun' => 70,
                'keterangan' => 'Jabatan fungsional dosen tertinggi',
            ],
            [
                'id' => 10,
                'jabatan_akademik_id' => 5,
                'pangkat_id' => 1,
                'kode' => 'DP',
                'nama_jabatan_fungsional' => 'Dosen Praktisi',
                'kode_jabatan_akademik' => 'DP',
                'pangkat' => 'III/a',
                'angka_kredit' => '100',
                'usia_pensiun' => 65,
                'keterangan' => 'Dosen dari kalangan praktisi/industri',
            ],
            [
                'id' => 11,
                'jabatan_akademik_id' => 6,
                'pangkat_id' => 1,
                'kode' => 'DTT',
                'nama_jabatan_fungsional' => 'Dosen Tidak Tetap',
                'kode_jabatan_akademik' => 'DT',
                'pangkat' => 'III/a',
                'angka_kredit' => '100',
                'usia_pensiun' => 65,
                'keterangan' => 'Dosen dengan status tidak tetap',
            ],
            [
                'id' => 12,
                'jabatan_akademik_id' => 7,
                'pangkat_id' => 1,
                'kode' => 'TA',
                'nama_jabatan_fungsional' => 'Tenaga Ahli',
                'kode_jabatan_akademik' => 'TA',
                'pangkat' => 'III/a',
                'angka_kredit' => '100',
                'usia_pensiun' => 65,
                'keterangan' => 'Tenaga ahli atau spesialis dalam bidang tertentu',
            ],
            [
                'id' => 13,
                'jabatan_akademik_id' => 8,
                'pangkat_id' => 1,
                'kode' => 'AD',
                'nama_jabatan_fungsional' => 'Asisten Dosen',
                'kode_jabatan_akademik' => 'AD',
                'pangkat' => 'III/a',
                'angka_kredit' => '50',
                'usia_pensiun' => 65,
                'keterangan' => 'Asisten yang membantu dosen dalam pengajaran',
            ],
            [
                'id' => 14,
                'jabatan_akademik_id' => 9,
                'pangkat_id' => 1,
                'kode' => 'TU',
                'nama_jabatan_fungsional' => 'Tutor',
                'kode_jabatan_akademik' => 'TU',
                'pangkat' => 'III/a',
                'angka_kredit' => '50',
                'usia_pensiun' => 65,
                'keterangan' => 'Pengajar tutorial atau praktikum',
            ],
            [
                'id' => 15,
                'jabatan_akademik_id' => 10,
                'pangkat_id' => 1,
                'kode' => 'PL',
                'nama_jabatan_fungsional' => 'Peneliti',
                'kode_jabatan_akademik' => 'PL',
                'pangkat' => 'III/a',
                'angka_kredit' => '100',
                'usia_pensiun' => 65,
                'keterangan' => 'Staf yang khusus melakukan penelitian',
            ],
        ];

        DB::table('simpeg_jabatan_fungsional')->insert($jabatanFungsional);
    }
}