<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SimpegMediaPublikasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mediaPublikasi = [
            ['nama' => 'AL-TADIB : Jurnal Kajian Ilmu Kependidikan'],
            ['nama' => 'Al Yasini : Jurnal Hasil Kajian dan Penelitian Bidang Keislaman dan Pendidikan'],
            ['nama' => 'Al-Manahij : Jurnal Kajian Hukum Islam'],
            // Tambahkan semua media publikasi lainnya di sini
            ['nama' => 'Al-Manahij: Jurnal Kajian Islam'],
            ['nama' => 'Al-Manar : Jurnal Kajian Alquran dan Hadis'],
            ['nama' => 'Al-Qisthu: Jurnal Kajian Ilmu-ilmu Hukum'],
            ['nama' => 'Al-Risalah : Forum Kajian Hukum dan Sosial Kemasyarakatan'],
            ['nama' => 'Analisa: Jurnal Pengkajian Masalah Sosial Keagamaan'],
            ['nama' => 'Anuva: Jurnal Kajian Budaya, Perpustakaan, dan Informasi'],
            ['nama' => 'At-Tarbawi: Jurnal Kajian Kependidikan Islam'],
            ['nama' => 'BASINDO : Jurnal Kajian Bahasa, Sastra Indonesia, dan Pembelajarannya'],
            ['nama' => 'BIBLIOTIKA : Jurnal Kajian Perpustakaan dan Informasi'],
            ['nama' => 'Barista : Jurnal Kajian Bahasa dan Pariwisata'],
            ['nama' => 'Basastra: Jurnal Kajian Bahasa dan Sastra Indonesia'],
            ['nama' => 'Bhineka Tunggal Ika : Kajian Teori dan Praktik Pendidikan PKn'],
            ['nama' => 'Brikolase : Jurnal Kajian Teori, Praktik dan Wacana Seni Budaya Rupa'],
            ['nama' => 'CENDEKIA : Jurnal Kajian Penelitian Pendidikan'],
            ['nama' => 'Cakrawala : Jurnal Kajian Manajemen Pendidikan Islam dan Studi Sosial'],
            ['nama' => 'Dewa Ruci: Jurnal Pengkajian dan Penciptaan Seni'],
            ['nama' => 'Dhammavicaya : Jurnal Pengkajian Dhamma'],
            ['nama' => 'Diglosia: Jurnal Kajian Bahasa, Sastra dan Pengajarannya'],
            ['nama' => 'Edcomtech : Jurnal Kajian Teknologi Pendidikan'],
            ['nama' => 'Edcomtech: Jurnal Kajian Teknologi Pendidikan'],
            ['nama' => 'Efisiensi : Kajian Ilmu Administrasi'],
            ['nama' => 'Ekonomi dan Bisnis: Berkala Publikasi Gagasan Konseptual, Hasil Penelitian, Kajian, dan Terapan Teori'],
            ['nama' => 'Endogami: Jurnal Ilmiah Kajian Antropologi'],
            ['nama' => 'FIKRI : Jurnal Kajian Agama, Sosial dan Budaya'],
            ['nama' => 'Fokus Bisnis: Media Pengkajian Manajemen dan Akuntansi'],
            ['nama' => 'Fokus Jurnal Kajian Keislaman dan Kemasyarakatan'],
            ['nama' => 'GEOGRAPHY : Jurnal Kajian, Penelitian dan Pengembangan Pendidikan'],
            ['nama' => 'GLOBAL CITIZEN Jurnal Ilmiah Kajian Pendidikan Kewarganegaraan'],
            ['nama' => 'Geodika: Jurnal Kajian Ilmu dan Pendidikan Geografi'],
            ['nama' => 'Hakam : Jurnal Kajian Hukum Islam dan Hukum Ekonomi Islam'],
            ['nama' => 'Historis : Jurnal Kajian, Penelitian dan Pengembangan Pendidikan Sejarah'],
            ['nama' => 'Humanika : Kajian Ilmiah Mata Kuliah Umum'],
            ['nama' => 'IBDA` : Jurnal Kajian Islam dan Budaya'],
            ['nama' => 'Ilmu Pendidikan: Jurnal Kajian Teori dan Praktik Kependidikan'],
            ['nama' => 'Indonesian Governance Journal (Kajian Politik-Pemerintahan)'],
            ['nama' => 'Inovasi Sekolah Dasar: Jurnal Kajian Pengembangan Pendidikan'],
            ['nama' => 'Invensi: Jurnal Penciptaan dan Pengkajian Seni'],
            ['nama' => 'Iqtishadia: Jurnal Kajian Ekonomi dan Bisnis Islam'],
            ['nama' => 'Islamic Review: Jurnal Riset dan Kajian Keislaman'],
            ['nama' => 'JAK (Jurnal Akuntansi) : Kajian Ilmiah Akuntansi'],
            ['nama' => 'JINOTEP (Jurnal Inovasi dan Teknologi Pembelajaran): Kajian dan Riset dalam Teknologi Pembelajaran'],
            ['nama' => 'JIP (Jurnal Ilmu Pemerintahan) : Kajian Ilmu Pemerintahan dan Politik Daerah'],
            ['nama' => 'JKPD (Jurnal Kajian Pendidikan Dasar)'],
            ['nama' => 'JKPM (Jurnal Kajian Pendidikan Matematika)'],
            ['nama' => 'JKTP: Jurnal Kajian Teknologi Pendidikan'],
            ['nama' => 'JPKS (Jurnal Pendidikan dan Kajian Seni)'],
            ['nama' => 'JURNAL EKONOMI PEMBANGUNAN: Kajian Masalah Ekonomi dan Pembangunan (JEP: KMEP)'],
            ['nama' => 'JURNAL KAJIAN TEKNIK ELEKTRO'],
            ['nama' => 'Journal An-Nafs: Kajian Penelitian Psikologi'],
            ['nama' => 'Journal of Government: Kajian Manajemen Pemerintahan dan Otonomi Daerah'],
            ['nama' => 'Jurnal Al- Bayan: Media Kajian dan Pengembangan Ilmu Dakwah'],
            ['nama' => 'Jurnal AGRISEP: Kajian Masalah Sosial Ekonomi Pertanian dan Agribisnis'],
            ['nama' => 'Jurnal AUDI : Jurnal Ilmiah Kajian Ilmu Anak dan Media Informasi PAUD'],
            ['nama' => 'Jurnal Agrisep : Kajian Masalah Sosial Ekonomi Pertanian dan Agribisnis'],
            ['nama' => 'Jurnal Biblio Couns Jurnal Kajian Konseling dan Pendidikan'],
            ['nama' => 'Jurnal Bisnis Dan Kajian Strategi Manajemen'],
            ['nama' => 'Jurnal Civic Education: Media Kajian Pancasila dan Kewarganegaraan'],
            ['nama' => 'Jurnal Civics: Media Kajian Kewarganegaraan'],
            ['nama' => 'Jurnal Ecoment Global, Kajian Bisnis dan Manajemen'],
            ['nama' => 'Jurnal Ekonomi Pembangunan : Kajian Masalah Ekonomi dan Pembangunan'],
            ['nama' => 'Jurnal Elementary : Kajian Teori dan Hasil Penelitian Pendidikan Sekolah Dasar'],
            ['nama' => 'Jurnal IQRA : Kajian Ilmu Pendidikan'],
            ['nama' => 'Jurnal IUS : Kajian Hukum dan Keadilan'],
            ['nama' => 'Jurnal Ilmiah Hukum DeJure: Kajian Ilmiah Hukum'],
            ['nama' => 'Jurnal Ilmu Komunikasi UHO : Jurnal Penelitian Kajian Ilmu Komunikasi dan Informasi'],
            ['nama' => 'Jurnal Imam Bonjol : Kajian Ilmu Informasi dan Perpustakaan'],
            ['nama' => 'Jurnal Kajian Akuntansi'],
            ['nama' => 'Jurnal Kajian Bali'],
            ['nama' => 'Jurnal Kajian Bali (Journal of Bali Studies)'],
            ['nama' => 'Jurnal Kajian Bimbingan dan Konseling'],
            ['nama' => 'Jurnal Kajian Ekonomi dan Pembangunan'],
            ['nama' => 'Jurnal Kajian Gender dan Anak'],
            ['nama' => 'Jurnal Kajian Ilmiah'],
            ['nama' => 'Jurnal Kajian Informasi & Perpustakaan'],
            ['nama' => 'Jurnal Kajian Komunikasi'],
            ['nama' => 'Jurnal Kajian Manajemen Bisnis'],
            ['nama' => 'Jurnal Kajian Manajemen Bisnis'],
            ['nama' => 'Jurnal Kajian Manajemen dan Kewirausahaan'],
            ['nama' => 'Jurnal Kajian Manajemen dan Wirausaha'],
            ['nama' => 'Jurnal Kajian Media'],
            ['nama' => 'Jurnal Kajian Pembaruan Hukum'],
            ['nama' => 'Jurnal Kajian Pembelajaran Matematika'],
            ['nama' => 'Jurnal Kajian Seni'],
            ['nama' => 'Jurnal Kajian Teknik Mesin'],
            ['nama' => 'Jurnal Kajian Veteriner'],
            ['nama' => 'Jurnal Kependidikan: Jurnal Hasil Penelitian dan Kajian Kepustakaan di Bidang Pendidikan, Pengajaran, dan Pembelajaran'],
            ['nama' => 'Jurnal Komunikasi dan Kajian Media'],
            ['nama' => 'Jurnal Mahkamah : Kajian Ilmu Hukum Dan Hukum Islam'],
            ['nama' => 'Jurnal Menara Ekonomi : Penelitian dan Kajian Ilmiah Bidang Ekonomi'],
            ['nama' => 'Jurnal Natapraja : Kajian Ilmu Administrasi Negara'],
            ['nama' => 'Jurnal PAUD: Kajian Teori dan Praktik Pendidikan Anak Usia Dini'],
            ['nama' => 'Jurnal Pembelajaran Biologi : Kajian Biologi dan Pembelajarannya'],
            ['nama' => 'Jurnal Penelitian Pendidikan Kimia: Kajian Hasil Penelitian Pendidikan Kimia'],
            ['nama' => 'Jurnal Penelitian dan Kajian Ilmiah Kesehatan Politeknik Medica Farma Husada Mataram'],
            ['nama' => 'Jurnal Pengkajian dan Pengembangan Teknologi Pertanian'],
            ['nama' => 'Jurnal Persada: Kajian Ilmu Pendidikan Dasar'],
            ['nama' => 'Jurnal Peurawi : Media Kajian Komunikasi Islam'],
            ['nama' => 'Jurnal Profit : Kajian Pendidikan Ekonomi dan Ilmu Ekonomi'],
            ['nama' => 'Jurnal Psikologi Pendidikan dan Konseling: Jurnal Kajian Psikologi Pendidikan dan Bimbingan Konseling'],
            ['nama' => 'Jurnal Pusaka : Media Kajian dan Pemikiran Islam'],
            ['nama' => 'Jurnal Review Pendidikan Dasar : Jurnal Kajian Pendidikan dan Hasil Penelitian'],
            ['nama' => 'Jurnal Riset dan Kajian Pendidikan Fisika'],
            ['nama' => 'Jurnal Silogisme: Kajian Ilmu Matematika dan Pembelajarannya'],
            ['nama' => 'Jurnal Tarbiyatuna : Kajian Pendidikan Islam'],
            ['nama' => 'Jurnal Wahana Kajian Pendidikan IPS'],
            ['nama' => 'KENOSIS: Jurnal Kajian Teologi'],
            ['nama' => 'KEUDA (Jurnal Kajian Ekonomi dan Keuangan Daerah)'],
            ['nama' => 'KLAUSA (Kajian Linguistik, Pembelajaran Bahasa, dan Sastra)'],
            ['nama' => 'Kajian Akuntansi'],
            ['nama' => 'Kajian Bisnis STIE Widya Wiwaha'],
            ['nama' => 'Kajian Ekonomi dan Keuangan'],
            ['nama' => 'Kajian Jurnalisme'],
            ['nama' => 'Kajian Linguistik'],
            ['nama' => 'Kajian Linguistik dan Sastra'],
            ['nama' => 'Keteg : Jurnal Pengetahuan, Pemikiran dan Kajian Tentang Bunyi'],
            ['nama' => 'Konseling Komprehensif: Kajian Teori dan Praktik Bimbingan dan Konseling'],
            ['nama' => 'Lensa : Kajian Kebahasaan, Kesusastraan, dan Budaya'],
            ['nama' => 'Lentera Pustaka: Jurnal Kajian Ilmu Perpustakaan, Informasi dan Kearsipan'],
            ['nama' => 'Lex Journal : Kajian Hukum dan Keadilan'],
            ['nama' => 'Local Wisdom : Jurnal Ilmiah Kajian Kearifan Lokal'],
            ['nama' => 'Lokabasa : Jurnal Kajian Bahasa, Sastra, dan Budaya Daerah serta Pengajarannya'],
            ['nama' => 'MUDARRISA: Jurnal Kajian Pendidikan Islam'],
            ['nama' => 'Madania (Kajian Keislaman)'],
            ['nama' => 'Madania : Jurnal Kajian Keislaman'],
            ['nama' => 'Mahkamah: Jurnal Kajian Hukum Islam'],
            ['nama' => 'Majalah Ilmiah Pengkajian Industri'],
            ['nama' => 'Masyarakat Madani: Jurnal Kajian Islam dan Pengembangan Masyarakat'],
            ['nama' => 'Media Syariah: Wahana Kajian Hukum Islam dan Pranata Sosial'],
            ['nama' => 'Media Trend: Berkala Kajian Ekonomi dan Studi Pembangunan'],
            ['nama' => 'Menara Ilmu : Jurnal Penelitian dan Kajian Ilmiah'],
            ['nama' => 'MetaKom : Jurnal Kajian Komunikasi'],
            ['nama' => 'Mimbar Pendidikan: Jurnal Indonesia untuk Kajian Pendidikan'],
            ['nama' => 'Misykat al-Anwar Jurnal Kajian Islam dan Masyarakat'],
            ['nama' => 'Naturalistic : Jurnal Kajian dan Penelitian Pendidikan dan Pembelajaran'],
            ['nama' => 'Nukhbatul Ulum : Jurnal Bidang Kajian Islam'],
            ['nama' => 'OIKOS: Jurnal Kajian Pendidikan Ekonomi dan Ilmu Ekonomi'],
            ['nama' => 'ORBITA: Jurnal Kajian, Inovasi dan Aplikasi Pendidikan Fisika'],
            ['nama' => 'PROMUSIKA : Jurnal Pengkajian, Penyajian, dan Penciptaan Musik'],
            ['nama' => 'Paedagoria : Jurnal Kajian, Penelitian dan Pengembangan Kependidikan'],
            ['nama' => 'Paradigma : Jurnal Kajian Budaya'],
            ['nama' => 'Parafrase: Jurnal Kajian Kebahasaan dan Kesastraan'],
            ['nama' => 'PrimEarly : Jurnal Kajian Pendidikan Dasar dan Anak Usia Dini (Journal of Primary and Early Childhood Education Studies)'],
            ['nama' => 'Prisma Sains : Jurnal Pengkajian Ilmu dan Pembelajaran Matematika dan IPA IKIP Mataram'],
            ['nama' => 'ProTVF: Jurnal Kajian Televisi dan Film'],
            ['nama' => 'Pustakaloka : Jurnal Kajian Informasi dan Perpustakaan'],
            ['nama' => 'SUHUF, Pengembangan Kajian Keislaman'],
            ['nama' => 'Sabda : Jurnal Kajian Kebudayaan'],
            ['nama' => 'Sainstech: Jurnal Penelitian dan Pengkajian Sains dan Teknologi'],
            ['nama' => 'Sangkep: Jurnal Kajian Sosial Keagamaan'],
            ['nama' => 'Satwika : Kajian Ilmu Budaya dan Perubahan Sosial'],
            ['nama' => 'Sekolah Dasar:Kajian Teori dan Praktik Pendidikan'],
            ['nama' => 'Sorai: Jurnal Pengkajian dan Penciptaan Musik'],
            ['nama' => 'Sosiologi: Jurnal Ilmiah Kajian Ilmu Sosial dan Budaya'],
            ['nama' => 'Swarnadwipa : Jurnal Kajian Sejarah, Sosial, Budaya, dan Pembelajarannya'],
            ['nama' => 'Tahdis: Jurnal Kajian Ilmu Al-Hadis'],
            ['nama' => 'Tonil: Jurnal Kajian Sastra, Teater, dan Sinema'],
            ['nama' => 'Translitera : Jurnal Kajian Komunikasi dan Studi Media'],
            ['nama' => 'Tumbuh Kembang : Kajian Teori dan Pembelajaran PAUD'],
            ['nama' => 'Virtuoso: Jurnal Pengkajian dan Penciptaan Musik'],
        ];

        DB::table('simpeg_media_publikasi')->insert($mediaPublikasi);
    }
}